SOE/Models/SOEModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SOE.Models
{
    public class SOEModel
    {

        public string txtURL { get; set; }

        public string txtArea { get; set; }

        public List<string> SOEOption { get; set; }

       
    }
}

SOE/Models/SOEResponseModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SOE.Models
{
    public class SOEResponseModel
    {
        public string ErrorMessage { get; set; }
        public Dictionary<string, int> CountOccurrence { get; set; }
        public Dictionary<string, int> MetaTagOccurrences { get; set; }
        public int? ExternaLinkCount { get; set; }
        public string OutputText { get; set; }
    }
}

SOE/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SOE.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

SOE/Controllers/SOEController.cs
using Business;
using SOE.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace SOE.Controllers
{
    public class SOEController : Controller
    {
        // GET: SOE
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]

        public ActionResult Index(SOEModel soe)
        {
            SOEResponseModel res = new SOEResponseModel();
            if (ModelState.IsValid)
            {
                List<string> stopWordsList = new List<string>() { "all", "at", "of" };
                SOEService svc = new SOEService();
                string InputText = soe.txtArea ?? string.Empty;
                if (!String.IsNullOrWhiteSpace(soe.txtURL))
                {
                    try
                    {
                        HttpWebRequest request = (HttpWebRequest)WebRequest.Create(soe.txtURL);
                        HttpWebResponse response = (HttpWebResponse)request.GetResponse();

                        if (response.StatusCode == HttpStatusCode.OK)
                        {
                            Stream receiveStream = response.GetResponseStream();
                            StreamReader readStream = null;

                            if (response.CharacterSet == null)
                            {
                                readStream = new StreamReader(receiveStream);
                            }
                            else
                            {
                                readStream = new StreamReader(receiveStream, Encoding.GetEncoding(response.CharacterSet));
                            }

                            InputText = readStream.ReadToEnd();
                            response.Close();
                            readStream.Close();
                        }
                    }
                    catch (System.UriFormatException uex)
                    {
                        res.ErrorMessage = "There was an error in the format of the url: " + soe.txtURL;

                    }
                    catch (System.Net.WebException wex)
                    {
                        res.ErrorMessage = string.Format("There was an error connecting to the url [{0}] [{1}] ", soe.txtURL, wex.Message);
                    }
                }
                if (!string.IsNullOrEmpty(InputText) && string.IsNullOrEmpty(res.ErrorMessage)) //No Error and InputText is not empty
                {
                    if (soe.SOEOption != null && soe.SOEOption.Any())
                    {
                        if (soe.SOEOption.Contains("StopwordCheck"))
                        {
                            res.OutputText = svc.RemoveWords(stopWordsList, InputText);
                        }
                        if (soe.SOEOption.Contains("OccurrenceCheck"))
                        {
                            res.CountOccurrence = svc.CountOccurrences(InputText);
                        }
                        if (soe.SOEOption.Contains("MetaCheck"))
                        {
                            res.MetaTagOccurrences = svc.CountMetaTagOccurrences(InputText);
                        }
                        if (soe.SOEOption.Contains("URLCheck"))
                        {
                            res.ExternaLinkCount = svc.ExternalLink(InputText);
                        }
                    }
                    else
                    {
                        res.ErrorMessage = "Please tick at least one check box";
                    }
                }
                else
                {
                    res.ErrorMessage = "Please enter Text or URL";
                }
            }
            else
            { res.ErrorMessage = "Invalid Input"; }
            return View(res);

        }
    }
}

SOE/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

SOE/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SOE/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

SOE/Views/SOE/Index.cshtml
@{
    ViewBag.Title = "Index";
}



@model SOE.Models.SOEResponseModel
<h2>SOE</h2>
@using (Html.BeginForm("Index", "SOE", FormMethod.Post))

{
    <div class="form-group">
        <label for="inpURL">URL</label>
        <input type="text" class="form-control" id="txtURL" name="txtURL" placeholder="Enter URL">
    </div>
    <div class="form-group">
        <label for="exampleFormControlTextarea1">Text Area</label>
        <textarea class="form-control" id="txtArea" name="txtArea" rows="3"></textarea>
    </div>
    <div class="form-check">
        <input type="checkbox" class="form-check-input" id="StopwordCheck" name="SOEOption" value="StopwordCheck">
        <label class="form-check-label" for="StopwordCheck">Remove Stop-Words</label>
    </div>
    <div class="form-check">
        <input type="checkbox" class="form-check-input" id="OccurrenceCheck" name="SOEOption" value="OccurrenceCheck">
        <label class="form-check-label" for="exampleCheck1">Word Occurrence</label>
    </div>
    <div class="form-check">
        <input type="checkbox" class="form-check-input" id="MetaCheck" name="SOEOption" value="MetaCheck">
        <label class="form-check-label" for="exampleCheck1">Meta Keyword Occurrence</label>
    </div>
    <div class="form-check">
        <input type="checkbox" class="form-check-input" id="URLCheck" name="SOEOption" value="URLCheck">
        <label class="form-check-label" for="exampleCheck1">External URL</label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
}
<p></p>
<p></p>
<div id="accordion">
    @if (Model != null)
    {
        if (Model.ErrorMessage != null)
        {
            <div class="alert alert-danger text-danger" role="alert">
                @Model.ErrorMessage
            </div>
        }

        if (Model.OutputText != null)
        {
            <div class="card">
                <div class="card-header" id="headingOne">
                    <h5 class="mb-0">
                        <button class="btn btn-link btn-primary collapsed" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            Remove Stop-words Result
                        </button>
                    </h5>
                </div>
                <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
                    <div class="card-body">
                        <textarea class="form-control" id="txtArea" name="txtOutputText" rows="3">@Model.OutputText</textarea>
                    </div>
                </div>
            </div>

        }
        if (Model.ExternaLinkCount != null)
        {
            <div class="alert alert-success" role="alert">
                Total Number of External Link detected is @Model.ExternaLinkCount
            </div>
        }

        if (Model.MetaTagOccurrences != null && Model.MetaTagOccurrences.Any())
        {
            <div class="card">
                <div class="card-header" id="headingTwo">
                    <h5 class="mb-0">
                        <button class="btn btn-link btn-primary collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                            Meta Keyword Occurrence Result
                        </button>
                    </h5>
                </div>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
                    <div class="card-body">
                        <table id="dtMetaTagOccurrences" class="table table-striped table-bordered table-sm" cellspacing="0">
                            <thead>
                                <tr>
                                    <th class="th-sm">
                                        Meta Keyword
                                    </th>
                                    <th class="th-sm">
                                        Occurrences
                                    </th>

                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var keyValue in Model.MetaTagOccurrences.Keys)
                                {
                                    <tr>
                                        <td>@keyValue</td>
                                        <td>@Model.MetaTagOccurrences[keyValue]</td>

                                    </tr>}

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>


            <script type="text/javascript">
                $(document).ready(function () {
                    $('#dtMetaTagOccurrences').DataTable();
                    $('.dataTables_length').addClass('bs-select');
                });</script>
        }
        @*else
            {
                <div class="alert alert-primary" role="alert">
                    No Meta Keyword Detected.<br />
                    Example Meta Keyword<br />
                      <b>&#60;meta name="keywords" content="HTML,CSS,XML,JavaScript"&#62;</b>
                </div>
            }*@

        if (Model.CountOccurrence != null && Model.CountOccurrence.Any())
        {
            <div class="card">
                <div class="card-header" id="headingThree">
                    <h5 class="mb-0">
                        <button class="btn btn-link btn-primary collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                            Word Occurrence Result
                        </button>
                    </h5>
                </div>
                <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
                    <div class="card-body">
                        <table id="dtCountOccurrence" class="table table-striped table-bordered table-sm" cellspacing="0">
                            <thead>
                                <tr>
                                    <th class="th-sm">
                                        Word
                                    </th>
                                    <th class="th-sm">
                                        Occurrences
                                    </th>

                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var keyValue in Model.CountOccurrence.Keys)
                                {
                                    <tr>
                                        <td>@keyValue</td>
                                        <td>@Model.CountOccurrence[keyValue]</td>

                                    </tr>}

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <script type="text/javascript">
                $(document).ready(function () {
                    $('#dtCountOccurrence').DataTable();
                    $('.dataTables_length').addClass('bs-select');
                });</script>
        }

    }
</div>

SOE/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <!-- MDBootstrap Datatables  -->
    <link href="/Content/addons/datatables.min.css" rel="stylesheet" />
    <!--MDBootstrap Datatables-->
    <script type="text/javascript" src="/Scripts/addons/datatables.min.js"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("SOE", "Index", "SOE")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

</body>
</html>